// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vQU939GjUi82K5u1iSBKF3
// Component: -pgjNYrnST
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Sidebar from "../../Sidebar"; // plasmic-import: yoRVhunlI-d/component
import SelectBoxPrimary from "../../SelectBoxPrimary"; // plasmic-import: 3HWfNZURm7l/component
import SelectBoxPrimary__Option from "../../SelectBoxPrimary__Option"; // plasmic-import: dmwcrBXAMAY/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: puPU6pgA-z/component
import AdminTable from "../../AdminTable"; // plasmic-import: tm5vSvyu3h/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_lime_hrm_front.module.css"; // plasmic-import: vQU939GjUi82K5u1iSBKF3/projectcss
import * as sty from "./PlasmicAdministration.module.css"; // plasmic-import: -pgjNYrnST/css

export type PlasmicAdministration__VariantMembers = {};

export type PlasmicAdministration__VariantsArgs = {};
type VariantPropType = keyof PlasmicAdministration__VariantsArgs;
export const PlasmicAdministration__VariantProps = new Array<VariantPropType>();

export type PlasmicAdministration__ArgsType = {};
type ArgPropType = keyof PlasmicAdministration__ArgsType;
export const PlasmicAdministration__ArgProps = new Array<ArgPropType>();

export type PlasmicAdministration__OverridesType = {
  root?: p.Flex<"div">;
  sidebar?: p.Flex<typeof Sidebar>;
  filterEmployees?: p.Flex<"div">;
  searchButton?: p.Flex<typeof ButtonPrimary>;
  usernameInput?: p.Flex<"input">;
  employeeNameInput?: p.Flex<"input">;
  adminSection?: p.Flex<"div">;
  tableButtons?: p.Flex<"div">;
  deleteButton?: p.Flex<"button">;
  buttonPrimary?: p.Flex<typeof ButtonPrimary>;
  adminTable?: p.Flex<typeof AdminTable>;
};

export interface DefaultAdministrationProps {
  className?: string;
}

function PlasmicAdministration__RenderFunc(props: {
  variants: PlasmicAdministration__VariantsArgs;
  args: PlasmicAdministration__ArgsType;
  overrides: PlasmicAdministration__OverridesType;
  dataFetches?: PlasmicAdministration__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Sidebar
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            className={classNames("__wab_instance", sty.sidebar)}
          />

          <div className={classNames(defaultcss.all, sty.freeBox__xUinI)}>
            <div
              data-plasmic-name={"filterEmployees"}
              data-plasmic-override={overrides.filterEmployees}
              className={classNames(defaultcss.all, sty.filterEmployees)}
            >
              <SelectBoxPrimary
                className={classNames(
                  "__wab_instance",
                  sty.selectBoxPrimary__h3JUv
                )}
              />

              <SelectBoxPrimary
                className={classNames(
                  "__wab_instance",
                  sty.selectBoxPrimary__x1J19
                )}
              />

              <ButtonPrimary
                data-plasmic-name={"searchButton"}
                data-plasmic-override={overrides.searchButton}
                className={classNames("__wab_instance", sty.searchButton)}
                prop={"Search"}
              />

              <input
                data-plasmic-name={"usernameInput"}
                data-plasmic-override={overrides.usernameInput}
                className={classNames(defaultcss.input, sty.usernameInput)}
                placeholder={"Some placeholder" as const}
                size={1 as const}
                type={"text" as const}
                value={"Some value" as const}
              />

              <input
                data-plasmic-name={"employeeNameInput"}
                data-plasmic-override={overrides.employeeNameInput}
                className={classNames(defaultcss.input, sty.employeeNameInput)}
                placeholder={"Some placeholder" as const}
                size={1 as const}
                type={"text" as const}
                value={"Some value" as const}
              />

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__dgG1I
                )}
              >
                {"Username"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__isZQi
                )}
              >
                {"User Role"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__qnbN
                )}
              >
                {"Employee Name"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox__gBg0
                )}
              >
                {"Status"}
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.freeBox___7JdPe
                )}
              >
                {"Administration"}
              </div>
            </div>

            <div
              data-plasmic-name={"adminSection"}
              data-plasmic-override={overrides.adminSection}
              className={classNames(defaultcss.all, sty.adminSection)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"tableButtons"}
                data-plasmic-override={overrides.tableButtons}
                hasGap={true}
                className={classNames(defaultcss.all, sty.tableButtons)}
              >
                <button
                  data-plasmic-name={"deleteButton"}
                  data-plasmic-override={overrides.deleteButton}
                  className={classNames(
                    defaultcss.button,
                    defaultcss.__wab_text,
                    sty.deleteButton
                  )}
                >
                  {"Delete"}
                </button>

                <ButtonPrimary
                  data-plasmic-name={"buttonPrimary"}
                  data-plasmic-override={overrides.buttonPrimary}
                  className={classNames("__wab_instance", sty.buttonPrimary)}
                  prop={"Add"}
                />
              </p.Stack>

              <AdminTable
                data-plasmic-name={"adminTable"}
                data-plasmic-override={overrides.adminTable}
                className={classNames("__wab_instance", sty.adminTable)}
              />
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sidebar",
    "filterEmployees",
    "searchButton",
    "usernameInput",
    "employeeNameInput",
    "adminSection",
    "tableButtons",
    "deleteButton",
    "buttonPrimary",
    "adminTable"
  ],
  sidebar: ["sidebar"],
  filterEmployees: [
    "filterEmployees",
    "searchButton",
    "usernameInput",
    "employeeNameInput"
  ],
  searchButton: ["searchButton"],
  usernameInput: ["usernameInput"],
  employeeNameInput: ["employeeNameInput"],
  adminSection: [
    "adminSection",
    "tableButtons",
    "deleteButton",
    "buttonPrimary",
    "adminTable"
  ],
  tableButtons: ["tableButtons", "deleteButton", "buttonPrimary"],
  deleteButton: ["deleteButton"],
  buttonPrimary: ["buttonPrimary"],
  adminTable: ["adminTable"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sidebar: typeof Sidebar;
  filterEmployees: "div";
  searchButton: typeof ButtonPrimary;
  usernameInput: "input";
  employeeNameInput: "input";
  adminSection: "div";
  tableButtons: "div";
  deleteButton: "button";
  buttonPrimary: typeof ButtonPrimary;
  adminTable: typeof AdminTable;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAdministration__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAdministration__VariantsArgs;
    args?: PlasmicAdministration__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAdministration__Fetches;
  } & Omit<PlasmicAdministration__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAdministration__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAdministration__ArgProps,
      internalVariantPropNames: PlasmicAdministration__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAdministration__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAdministration";
  } else {
    func.displayName = `PlasmicAdministration.${nodeName}`;
  }
  return func;
}

export const PlasmicAdministration = Object.assign(
  // Top-level PlasmicAdministration renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sidebar: makeNodeComponent("sidebar"),
    filterEmployees: makeNodeComponent("filterEmployees"),
    searchButton: makeNodeComponent("searchButton"),
    usernameInput: makeNodeComponent("usernameInput"),
    employeeNameInput: makeNodeComponent("employeeNameInput"),
    adminSection: makeNodeComponent("adminSection"),
    tableButtons: makeNodeComponent("tableButtons"),
    deleteButton: makeNodeComponent("deleteButton"),
    buttonPrimary: makeNodeComponent("buttonPrimary"),
    adminTable: makeNodeComponent("adminTable"),

    // Metadata about props expected for PlasmicAdministration
    internalVariantProps: PlasmicAdministration__VariantProps,
    internalArgProps: PlasmicAdministration__ArgProps
  }
);

export default PlasmicAdministration;
/* prettier-ignore-end */
