// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vQU939GjUi82K5u1iSBKF3
// Component: PlxKiMP25T
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_lime_hrm_front.module.css"; // plasmic-import: vQU939GjUi82K5u1iSBKF3/projectcss
import * as sty from "./PlasmicLeaveapply.module.css"; // plasmic-import: PlxKiMP25T/css

export type PlasmicLeaveapply__VariantMembers = {};

export type PlasmicLeaveapply__VariantsArgs = {};
type VariantPropType = keyof PlasmicLeaveapply__VariantsArgs;
export const PlasmicLeaveapply__VariantProps = new Array<VariantPropType>();

export type PlasmicLeaveapply__ArgsType = {};
type ArgPropType = keyof PlasmicLeaveapply__ArgsType;
export const PlasmicLeaveapply__ArgProps = new Array<ArgPropType>();

export type PlasmicLeaveapply__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultLeaveapplyProps {
  className?: string;
}

function PlasmicLeaveapply__RenderFunc(props: {
  variants: PlasmicLeaveapply__VariantsArgs;
  args: PlasmicLeaveapply__ArgsType;
  overrides: PlasmicLeaveapply__OverridesType;
  dataFetches?: PlasmicLeaveapply__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicLeaveapply__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicLeaveapply__VariantsArgs;
    args?: PlasmicLeaveapply__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicLeaveapply__Fetches;
  } & Omit<PlasmicLeaveapply__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicLeaveapply__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicLeaveapply__ArgProps,
      internalVariantPropNames: PlasmicLeaveapply__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicLeaveapply__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicLeaveapply";
  } else {
    func.displayName = `PlasmicLeaveapply.${nodeName}`;
  }
  return func;
}

export const PlasmicLeaveapply = Object.assign(
  // Top-level PlasmicLeaveapply renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicLeaveapply
    internalVariantProps: PlasmicLeaveapply__VariantProps,
    internalArgProps: PlasmicLeaveapply__ArgProps
  }
);

export default PlasmicLeaveapply;
/* prettier-ignore-end */
