// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vQU939GjUi82K5u1iSBKF3
// Component: 06awOUIVXL
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import CheckboxPrimary from "../../CheckboxPrimary"; // plasmic-import: txP424hXELb/component
import ButtonPrimary from "../../ButtonPrimary"; // plasmic-import: puPU6pgA-z/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_lime_hrm_front.module.css"; // plasmic-import: vQU939GjUi82K5u1iSBKF3/projectcss
import * as sty from "./PlasmicRecruitmentTable.module.css"; // plasmic-import: 06awOUIVXL/css

export type PlasmicRecruitmentTable__VariantMembers = {};

export type PlasmicRecruitmentTable__VariantsArgs = {};
type VariantPropType = keyof PlasmicRecruitmentTable__VariantsArgs;
export const PlasmicRecruitmentTable__VariantProps =
  new Array<VariantPropType>();

export type PlasmicRecruitmentTable__ArgsType = {};
type ArgPropType = keyof PlasmicRecruitmentTable__ArgsType;
export const PlasmicRecruitmentTable__ArgProps = new Array<ArgPropType>();

export type PlasmicRecruitmentTable__OverridesType = {
  root?: p.Flex<"div">;
  tableHeaders?: p.Flex<"div">;
  rowContent?: p.Flex<"div">;
  checkboxDiv?: p.Flex<"div">;
  buttonDiv?: p.Flex<"div">;
  rowContent2?: p.Flex<"div">;
  checkboxDiv2?: p.Flex<"div">;
  buttonDiv2?: p.Flex<"div">;
  rowContent3?: p.Flex<"div">;
  checkboxDiv3?: p.Flex<"div">;
  buttonDiv3?: p.Flex<"div">;
  rowContent4?: p.Flex<"div">;
  checkboxDiv4?: p.Flex<"div">;
  buttonDiv4?: p.Flex<"div">;
  rowContent5?: p.Flex<"div">;
  checkboxDiv5?: p.Flex<"div">;
  buttonDiv5?: p.Flex<"div">;
  rowContent6?: p.Flex<"div">;
  checkboxDiv6?: p.Flex<"div">;
  buttonDiv6?: p.Flex<"div">;
};

export interface DefaultRecruitmentTableProps {
  className?: string;
}

function PlasmicRecruitmentTable__RenderFunc(props: {
  variants: PlasmicRecruitmentTable__VariantsArgs;
  args: PlasmicRecruitmentTable__ArgsType;
  overrides: PlasmicRecruitmentTable__OverridesType;
  dataFetches?: PlasmicRecruitmentTable__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"tableHeaders"}
        data-plasmic-override={overrides.tableHeaders}
        className={classNames(defaultcss.all, sty.tableHeaders)}
      >
        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__g9In
          )}
        >
          {"Select"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__fkKDd
          )}
        >
          {"Job Title"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__afJe
          )}
        >
          {"Candidate"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__mxVhy
          )}
        >
          {"Priority"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___2L18R
          )}
        >
          {"Hiring Manager"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___7P64W
          )}
        >
          {"Status"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__bawcC
          )}
        >
          {"Resume"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__hSazc
          )}
        >
          {"Date"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent"}
        data-plasmic-override={overrides.rowContent}
        className={classNames(defaultcss.all, sty.rowContent)}
      >
        <div
          data-plasmic-name={"checkboxDiv"}
          data-plasmic-override={overrides.checkboxDiv}
          className={classNames(defaultcss.all, sty.checkboxDiv)}
        >
          <CheckboxPrimary
            className={classNames("__wab_instance", sty.checkboxPrimary__yyiuI)}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__pPtq9
          )}
        >
          {"SWE Intern"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__bHm3
          )}
        >
          {"Roger Foreman"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__mz3Qt
          )}
        >
          {"High"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__udtRv
          )}
        >
          {"Piratla"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__iu6Ic
          )}
        >
          {"Interview"}
        </div>

        <div
          data-plasmic-name={"buttonDiv"}
          data-plasmic-override={overrides.buttonDiv}
          className={classNames(defaultcss.all, sty.buttonDiv)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary__i4O)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__neDrl
          )}
        >
          {"07/12/2021"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent2"}
        data-plasmic-override={overrides.rowContent2}
        className={classNames(defaultcss.all, sty.rowContent2)}
      >
        <div
          data-plasmic-name={"checkboxDiv2"}
          data-plasmic-override={overrides.checkboxDiv2}
          className={classNames(defaultcss.all, sty.checkboxDiv2)}
        >
          <CheckboxPrimary
            className={classNames("__wab_instance", sty.checkboxPrimary__qY3Xj)}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__imTzK
          )}
        >
          {"Graphic Design"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__jlE32
          )}
        >
          {"Jane Doe"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__odp7L
          )}
        >
          {"Low"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__jdhFb
          )}
        >
          {"Raikman"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___42OIy
          )}
        >
          {"Offer Letter"}
        </div>

        <div
          data-plasmic-name={"buttonDiv2"}
          data-plasmic-override={overrides.buttonDiv2}
          className={classNames(defaultcss.all, sty.buttonDiv2)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary__laUsL)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__ypvxC
          )}
        >
          {"07/12/2021"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent3"}
        data-plasmic-override={overrides.rowContent3}
        className={classNames(defaultcss.all, sty.rowContent3)}
      >
        <div
          data-plasmic-name={"checkboxDiv3"}
          data-plasmic-override={overrides.checkboxDiv3}
          className={classNames(defaultcss.all, sty.checkboxDiv3)}
        >
          <CheckboxPrimary
            className={classNames("__wab_instance", sty.checkboxPrimary__xnJfH)}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__jmM2A
          )}
        >
          {"FSW Intern"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__fDoYh
          )}
        >
          {"John Doe"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__sxm4Z
          )}
        >
          {"Mid"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__ijC6B
          )}
        >
          {"Piratla"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__xFVok
          )}
        >
          {"Indeed"}
        </div>

        <div
          data-plasmic-name={"buttonDiv3"}
          data-plasmic-override={overrides.buttonDiv3}
          className={classNames(defaultcss.all, sty.buttonDiv3)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary___1Rfvh)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__bKaNq
          )}
        >
          {"07/10/2021"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent4"}
        data-plasmic-override={overrides.rowContent4}
        className={classNames(defaultcss.all, sty.rowContent4)}
      >
        <div
          data-plasmic-name={"checkboxDiv4"}
          data-plasmic-override={overrides.checkboxDiv4}
          className={classNames(defaultcss.all, sty.checkboxDiv4)}
        >
          <CheckboxPrimary
            className={classNames("__wab_instance", sty.checkboxPrimary__kQYr)}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___0PueM
          )}
        >
          {"Graphic Design"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__tVo2P
          )}
        >
          {"Billy Bob"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__mSmlz
          )}
        >
          {"Low"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___7Myp3
          )}
        >
          {"Raikman"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__zNwyN
          )}
        >
          {"Indeed"}
        </div>

        <div
          data-plasmic-name={"buttonDiv4"}
          data-plasmic-override={overrides.buttonDiv4}
          className={classNames(defaultcss.all, sty.buttonDiv4)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary__lPv2V)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__blIbV
          )}
        >
          {"07/01/2021"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent5"}
        data-plasmic-override={overrides.rowContent5}
        className={classNames(defaultcss.all, sty.rowContent5)}
      >
        <div
          data-plasmic-name={"checkboxDiv5"}
          data-plasmic-override={overrides.checkboxDiv5}
          className={classNames(defaultcss.all, sty.checkboxDiv5)}
        >
          <CheckboxPrimary
            className={classNames("__wab_instance", sty.checkboxPrimary__brfkm)}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__cHb0H
          )}
        >
          {"Graphic Design"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___2Js7U
          )}
        >
          {"Ralph Norman"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__hDrmX
          )}
        >
          {"Mid"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__tmqH9
          )}
        >
          {"Raikman"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox___1RtDr
          )}
        >
          {"Offer Letter"}
        </div>

        <div
          data-plasmic-name={"buttonDiv5"}
          data-plasmic-override={overrides.buttonDiv5}
          className={classNames(defaultcss.all, sty.buttonDiv5)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary__ec4Jt)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__iFo6
          )}
        >
          {"07/01/2021"}
        </div>
      </div>

      <div
        data-plasmic-name={"rowContent6"}
        data-plasmic-override={overrides.rowContent6}
        className={classNames(defaultcss.all, sty.rowContent6)}
      >
        <div
          data-plasmic-name={"checkboxDiv6"}
          data-plasmic-override={overrides.checkboxDiv6}
          className={classNames(defaultcss.all, sty.checkboxDiv6)}
        >
          <CheckboxPrimary
            className={classNames(
              "__wab_instance",
              sty.checkboxPrimary___9DgHj
            )}
          >
            {null}
          </CheckboxPrimary>
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__runCe
          )}
        >
          {"FSW Intern"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__tPxZk
          )}
        >
          {"Jeff Spears"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__bZ16Q
          )}
        >
          {"Mid"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__h3SEc
          )}
        >
          {"Piratla"}
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__q2GyZ
          )}
        >
          {"Interview"}
        </div>

        <div
          data-plasmic-name={"buttonDiv6"}
          data-plasmic-override={overrides.buttonDiv6}
          className={classNames(defaultcss.all, sty.buttonDiv6)}
        >
          <ButtonPrimary
            className={classNames("__wab_instance", sty.buttonPrimary__xg7Xt)}
            prop={"Download"}
          />
        </div>

        <div
          className={classNames(
            defaultcss.all,
            defaultcss.__wab_text,
            sty.freeBox__t2Gja
          )}
        >
          {"06/21/2021"}
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "tableHeaders",
    "rowContent",
    "checkboxDiv",
    "buttonDiv",
    "rowContent2",
    "checkboxDiv2",
    "buttonDiv2",
    "rowContent3",
    "checkboxDiv3",
    "buttonDiv3",
    "rowContent4",
    "checkboxDiv4",
    "buttonDiv4",
    "rowContent5",
    "checkboxDiv5",
    "buttonDiv5",
    "rowContent6",
    "checkboxDiv6",
    "buttonDiv6"
  ],
  tableHeaders: ["tableHeaders"],
  rowContent: ["rowContent", "checkboxDiv", "buttonDiv"],
  checkboxDiv: ["checkboxDiv"],
  buttonDiv: ["buttonDiv"],
  rowContent2: ["rowContent2", "checkboxDiv2", "buttonDiv2"],
  checkboxDiv2: ["checkboxDiv2"],
  buttonDiv2: ["buttonDiv2"],
  rowContent3: ["rowContent3", "checkboxDiv3", "buttonDiv3"],
  checkboxDiv3: ["checkboxDiv3"],
  buttonDiv3: ["buttonDiv3"],
  rowContent4: ["rowContent4", "checkboxDiv4", "buttonDiv4"],
  checkboxDiv4: ["checkboxDiv4"],
  buttonDiv4: ["buttonDiv4"],
  rowContent5: ["rowContent5", "checkboxDiv5", "buttonDiv5"],
  checkboxDiv5: ["checkboxDiv5"],
  buttonDiv5: ["buttonDiv5"],
  rowContent6: ["rowContent6", "checkboxDiv6", "buttonDiv6"],
  checkboxDiv6: ["checkboxDiv6"],
  buttonDiv6: ["buttonDiv6"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  tableHeaders: "div";
  rowContent: "div";
  checkboxDiv: "div";
  buttonDiv: "div";
  rowContent2: "div";
  checkboxDiv2: "div";
  buttonDiv2: "div";
  rowContent3: "div";
  checkboxDiv3: "div";
  buttonDiv3: "div";
  rowContent4: "div";
  checkboxDiv4: "div";
  buttonDiv4: "div";
  rowContent5: "div";
  checkboxDiv5: "div";
  buttonDiv5: "div";
  rowContent6: "div";
  checkboxDiv6: "div";
  buttonDiv6: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRecruitmentTable__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRecruitmentTable__VariantsArgs;
    args?: PlasmicRecruitmentTable__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicRecruitmentTable__Fetches;
  } & Omit<PlasmicRecruitmentTable__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRecruitmentTable__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRecruitmentTable__ArgProps,
      internalVariantPropNames: PlasmicRecruitmentTable__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicRecruitmentTable__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRecruitmentTable";
  } else {
    func.displayName = `PlasmicRecruitmentTable.${nodeName}`;
  }
  return func;
}

export const PlasmicRecruitmentTable = Object.assign(
  // Top-level PlasmicRecruitmentTable renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    tableHeaders: makeNodeComponent("tableHeaders"),
    rowContent: makeNodeComponent("rowContent"),
    checkboxDiv: makeNodeComponent("checkboxDiv"),
    buttonDiv: makeNodeComponent("buttonDiv"),
    rowContent2: makeNodeComponent("rowContent2"),
    checkboxDiv2: makeNodeComponent("checkboxDiv2"),
    buttonDiv2: makeNodeComponent("buttonDiv2"),
    rowContent3: makeNodeComponent("rowContent3"),
    checkboxDiv3: makeNodeComponent("checkboxDiv3"),
    buttonDiv3: makeNodeComponent("buttonDiv3"),
    rowContent4: makeNodeComponent("rowContent4"),
    checkboxDiv4: makeNodeComponent("checkboxDiv4"),
    buttonDiv4: makeNodeComponent("buttonDiv4"),
    rowContent5: makeNodeComponent("rowContent5"),
    checkboxDiv5: makeNodeComponent("checkboxDiv5"),
    buttonDiv5: makeNodeComponent("buttonDiv5"),
    rowContent6: makeNodeComponent("rowContent6"),
    checkboxDiv6: makeNodeComponent("checkboxDiv6"),
    buttonDiv6: makeNodeComponent("buttonDiv6"),

    // Metadata about props expected for PlasmicRecruitmentTable
    internalVariantProps: PlasmicRecruitmentTable__VariantProps,
    internalArgProps: PlasmicRecruitmentTable__ArgProps
  }
);

export default PlasmicRecruitmentTable;
/* prettier-ignore-end */
