// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vQU939GjUi82K5u1iSBKF3
// Component: 9Of3WWIskv
import * as React from "react";

import * as p from "@plasmicapp/react-web";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Sidebar from "../../Sidebar"; // plasmic-import: yoRVhunlI-d/component
import ApplyLeave from "../../ApplyLeave"; // plasmic-import: exv2JUik8JK/component
import SelectBoxPrimary__OptionGroup from "../../SelectBoxPrimary__OptionGroup"; // plasmic-import: XomSqMHtbQj/component
import SelectBoxPrimary__Option from "../../SelectBoxPrimary__Option"; // plasmic-import: dmwcrBXAMAY/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_lime_hrm_front.module.css"; // plasmic-import: vQU939GjUi82K5u1iSBKF3/projectcss
import * as sty from "./PlasmicAssignleave.module.css"; // plasmic-import: 9Of3WWIskv/css

export type PlasmicAssignleave__VariantMembers = {};

export type PlasmicAssignleave__VariantsArgs = {};
type VariantPropType = keyof PlasmicAssignleave__VariantsArgs;
export const PlasmicAssignleave__VariantProps = new Array<VariantPropType>();

export type PlasmicAssignleave__ArgsType = {};
type ArgPropType = keyof PlasmicAssignleave__ArgsType;
export const PlasmicAssignleave__ArgProps = new Array<ArgPropType>();

export type PlasmicAssignleave__OverridesType = {
  root?: p.Flex<"div">;
  sidebar?: p.Flex<typeof Sidebar>;
  applyLeave?: p.Flex<typeof ApplyLeave>;
  applylink?: p.Flex<"a">;
  assign?: p.Flex<"a">;
  myleave?: p.Flex<"a">;
  leaveist?: p.Flex<"a">;
  reports?: p.Flex<"a">;
  rowWrapper?: p.Flex<"div">;
  employeeName?: p.Flex<"label">;
  optionGroup?: p.Flex<typeof SelectBoxPrimary__OptionGroup>;
};

export interface DefaultAssignleaveProps {
  className?: string;
}

function PlasmicAssignleave__RenderFunc(props: {
  variants: PlasmicAssignleave__VariantsArgs;
  args: PlasmicAssignleave__ArgsType;
  overrides: PlasmicAssignleave__OverridesType;
  dataFetches?: PlasmicAssignleave__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  return (
    <React.Fragment>
      {}
      {}

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <Sidebar
            data-plasmic-name={"sidebar"}
            data-plasmic-override={overrides.sidebar}
            className={classNames("__wab_instance", sty.sidebar)}
          />

          <ApplyLeave
            data-plasmic-name={"applyLeave"}
            data-plasmic-override={overrides.applyLeave}
            className={classNames("__wab_instance", sty.applyLeave)}
          >
            <div className={classNames(defaultcss.all, sty.freeBox__i2Mew)}>
              <a
                data-plasmic-name={"applylink"}
                data-plasmic-override={overrides.applylink}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.applylink
                )}
                href={"/" as const}
              >
                {"Apply"}
              </a>

              <a
                data-plasmic-name={"assign"}
                data-plasmic-override={overrides.assign}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.assign
                )}
                href={"/" as const}
              >
                {"Assign Leave"}
              </a>

              <a
                data-plasmic-name={"myleave"}
                data-plasmic-override={overrides.myleave}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.myleave
                )}
                href={"/leave:myleave" as const}
              >
                {"My Leave"}
              </a>

              <a
                data-plasmic-name={"leaveist"}
                data-plasmic-override={overrides.leaveist}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.leaveist
                )}
              >
                {"Leave List"}
              </a>

              <a
                data-plasmic-name={"reports"}
                data-plasmic-override={overrides.reports}
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.reports
                )}
                href={"/leave:report" as const}
              >
                {"Reports"}
              </a>
            </div>

            <div className={classNames(defaultcss.all, sty.freeBox__qIdpx)}>
              <div className={classNames(defaultcss.all, sty.freeBox__nXqlz)}>
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___5D305
                  )}
                >
                  {"Assign Leave"}
                </div>
              </div>

              <p.Stack
                as={"div"}
                data-plasmic-name={"rowWrapper"}
                data-plasmic-override={overrides.rowWrapper}
                hasGap={true}
                className={classNames(defaultcss.all, sty.rowWrapper)}
              >
                <label
                  data-plasmic-name={"employeeName"}
                  data-plasmic-override={overrides.employeeName}
                  className={classNames(defaultcss.all, sty.employeeName)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.freeBox___1TiaT
                    )}
                  >
                    {"Employee Name"}
                  </div>
                </label>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox__tzqFp
                  )}
                >
                  {"Type here.."}
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.freeBox__mt4X4)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.freeBox___2Sj8I
                  )}
                >
                  {"Leave Type"}
                </div>

                <SelectBoxPrimary__OptionGroup
                  data-plasmic-name={"optionGroup"}
                  data-plasmic-override={overrides.optionGroup}
                  className={classNames("__wab_instance", sty.optionGroup)}
                />
              </p.Stack>
            </div>
          </ApplyLeave>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "sidebar",
    "applyLeave",
    "applylink",
    "assign",
    "myleave",
    "leaveist",
    "reports",
    "rowWrapper",
    "employeeName",
    "optionGroup"
  ],
  sidebar: ["sidebar"],
  applyLeave: [
    "applyLeave",
    "applylink",
    "assign",
    "myleave",
    "leaveist",
    "reports",
    "rowWrapper",
    "employeeName",
    "optionGroup"
  ],
  applylink: ["applylink"],
  assign: ["assign"],
  myleave: ["myleave"],
  leaveist: ["leaveist"],
  reports: ["reports"],
  rowWrapper: ["rowWrapper", "employeeName"],
  employeeName: ["employeeName"],
  optionGroup: ["optionGroup"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  sidebar: typeof Sidebar;
  applyLeave: typeof ApplyLeave;
  applylink: "a";
  assign: "a";
  myleave: "a";
  leaveist: "a";
  reports: "a";
  rowWrapper: "div";
  employeeName: "label";
  optionGroup: typeof SelectBoxPrimary__OptionGroup;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicAssignleave__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicAssignleave__VariantsArgs;
    args?: PlasmicAssignleave__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicAssignleave__Fetches;
  } & Omit<PlasmicAssignleave__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicAssignleave__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicAssignleave__ArgProps,
      internalVariantPropNames: PlasmicAssignleave__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicAssignleave__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicAssignleave";
  } else {
    func.displayName = `PlasmicAssignleave.${nodeName}`;
  }
  return func;
}

export const PlasmicAssignleave = Object.assign(
  // Top-level PlasmicAssignleave renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    sidebar: makeNodeComponent("sidebar"),
    applyLeave: makeNodeComponent("applyLeave"),
    applylink: makeNodeComponent("applylink"),
    assign: makeNodeComponent("assign"),
    myleave: makeNodeComponent("myleave"),
    leaveist: makeNodeComponent("leaveist"),
    reports: makeNodeComponent("reports"),
    rowWrapper: makeNodeComponent("rowWrapper"),
    employeeName: makeNodeComponent("employeeName"),
    optionGroup: makeNodeComponent("optionGroup"),

    // Metadata about props expected for PlasmicAssignleave
    internalVariantProps: PlasmicAssignleave__VariantProps,
    internalArgProps: PlasmicAssignleave__ArgProps
  }
);

export default PlasmicAssignleave;
/* prettier-ignore-end */
