// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: vQU939GjUi82K5u1iSBKF3
// Component: 3HWfNZURm7l
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as pp from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import SelectBoxPrimary__Overlay from "../../SelectBoxPrimary__Overlay"; // plasmic-import: 2So9Rk1rQd8/component
import SelectBoxPrimary__Option from "../../SelectBoxPrimary__Option"; // plasmic-import: dmwcrBXAMAY/component

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_lime_hrm_front.module.css"; // plasmic-import: vQU939GjUi82K5u1iSBKF3/projectcss
import * as sty from "./PlasmicSelectBoxPrimary.module.css"; // plasmic-import: 3HWfNZURm7l/css

import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: aQwNVAvIoHl/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: 66VWCPv-g18/icon

export type PlasmicSelectBoxPrimary__VariantMembers = {
  showPlaceholder: "showPlaceholder";
  isOpen: "isOpen";
  isDisabled: "isDisabled";
};

export type PlasmicSelectBoxPrimary__VariantsArgs = {
  showPlaceholder?: SingleBooleanChoiceArg<"showPlaceholder">;
  isOpen?: SingleBooleanChoiceArg<"isOpen">;
  isDisabled?: SingleBooleanChoiceArg<"isDisabled">;
};

type VariantPropType = keyof PlasmicSelectBoxPrimary__VariantsArgs;
export const PlasmicSelectBoxPrimary__VariantProps = new Array<VariantPropType>(
  "showPlaceholder",
  "isOpen",
  "isDisabled"
);

export type PlasmicSelectBoxPrimary__ArgsType = {
  selectedContent?: React.ReactNode;
  placeholder?: React.ReactNode;
  children?: React.ReactNode;
  value?: string;
  name?: string;
};

type ArgPropType = keyof PlasmicSelectBoxPrimary__ArgsType;
export const PlasmicSelectBoxPrimary__ArgProps = new Array<ArgPropType>(
  "selectedContent",
  "placeholder",
  "children",
  "value",
  "name"
);

export type PlasmicSelectBoxPrimary__OverridesType = {
  root?: p.Flex<"div">;
  trigger?: p.Flex<"button">;
  contentContainer?: p.Flex<"div">;
  dropdownIcon?: p.Flex<"svg">;
  overlay?: p.Flex<typeof SelectBoxPrimary__Overlay>;
  optionsContainer?: p.Flex<"div">;
};

export interface DefaultSelectBoxPrimaryProps extends pp.BaseSelectProps {}

const PlasmicSelectBoxPrimaryContext = React.createContext<
  | undefined
  | {
      variants: PlasmicSelectBoxPrimary__VariantsArgs;
      args: PlasmicSelectBoxPrimary__ArgsType;
    }
>(undefined);

function PlasmicSelectBoxPrimary__RenderFunc(props: {
  variants: PlasmicSelectBoxPrimary__VariantsArgs;
  args: PlasmicSelectBoxPrimary__ArgsType;
  overrides: PlasmicSelectBoxPrimary__OverridesType;
  dataFetches?: PlasmicSelectBoxPrimary__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const [isRootFocusVisibleWithin, triggerRootFocusVisibleWithinProps] =
    useTrigger("useFocusVisibleWithin", {
      isTextInput: false
    });

  const triggers = {
    focusVisibleWithin_root: isRootFocusVisibleWithin
  };

  return (
    <PlasmicSelectBoxPrimaryContext.Provider value={{ variants, args }}>
      <div
        data-plasmic-name={"root"}
        data-plasmic-override={overrides.root}
        data-plasmic-root={true}
        data-plasmic-for-node={forNode}
        className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
          [sty.root__isOpen]: hasVariant(variants, "isOpen", "isOpen")
        })}
        data-plasmic-trigger-props={[triggerRootFocusVisibleWithinProps]}
      >
        <p.Stack
          as={"button"}
          data-plasmic-name={"trigger"}
          data-plasmic-override={overrides.trigger}
          hasGap={true}
          className={classNames(defaultcss.button, sty.trigger, {
            [sty.trigger_____focusVisibleWithin]:
              triggers.focusVisibleWithin_root,
            [sty.trigger__isDisabled]: hasVariant(
              variants,
              "isDisabled",
              "isDisabled"
            ),
            [sty.trigger__isOpen]: hasVariant(variants, "isOpen", "isOpen")
          })}
          disabled={
            hasVariant(variants, "isDisabled", "isDisabled") ? true : undefined
          }
        >
          <div
            data-plasmic-name={"contentContainer"}
            data-plasmic-override={overrides.contentContainer}
            className={classNames(defaultcss.all, sty.contentContainer, {
              [sty.contentContainer__isDisabled]: hasVariant(
                variants,
                "isDisabled",
                "isDisabled"
              ),
              [sty.contentContainer__showPlaceholder]: hasVariant(
                variants,
                "showPlaceholder",
                "showPlaceholder"
              )
            })}
          >
            {(
              hasVariant(variants, "showPlaceholder", "showPlaceholder")
                ? false
                : true
            )
              ? p.renderPlasmicSlot({
                  defaultContents: "Selected",
                  value: args.selectedContent,
                  className: classNames(sty.slotSelectedContent, {
                    [sty.slotSelectedContent__isDisabled]: hasVariant(
                      variants,
                      "isDisabled",
                      "isDisabled"
                    ),
                    [sty.slotSelectedContent__isOpen]: hasVariant(
                      variants,
                      "isOpen",
                      "isOpen"
                    ),
                    [sty.slotSelectedContent__showPlaceholder]: hasVariant(
                      variants,
                      "showPlaceholder",
                      "showPlaceholder"
                    )
                  })
                })
              : null}
            {(
              hasVariant(variants, "showPlaceholder", "showPlaceholder")
                ? true
                : false
            )
              ? p.renderPlasmicSlot({
                  defaultContents: "Select…",
                  value: args.placeholder,
                  className: classNames(sty.slotPlaceholder, {
                    [sty.slotPlaceholder__showPlaceholder]: hasVariant(
                      variants,
                      "showPlaceholder",
                      "showPlaceholder"
                    )
                  })
                })
              : null}
          </div>

          <p.PlasmicIcon
            data-plasmic-name={"dropdownIcon"}
            data-plasmic-override={overrides.dropdownIcon}
            PlasmicIconType={
              hasVariant(variants, "isOpen", "isOpen") ? Icon5Icon : Icon4Icon
            }
            className={classNames(defaultcss.all, sty.dropdownIcon, {
              [sty.dropdownIcon_____focusVisibleWithin]:
                triggers.focusVisibleWithin_root,
              [sty.dropdownIcon__isOpen]: hasVariant(
                variants,
                "isOpen",
                "isOpen"
              )
            })}
            role={"img"}
          />
        </p.Stack>

        {(hasVariant(variants, "isOpen", "isOpen") ? true : false) ? (
          <SelectBoxPrimary__Overlay
            data-plasmic-name={"overlay"}
            data-plasmic-override={overrides.overlay}
            className={classNames("__wab_instance", sty.overlay, {
              [sty.overlay__isOpen]: hasVariant(variants, "isOpen", "isOpen")
            })}
            relativePlacement={"bottom" as const}
          >
            <div
              data-plasmic-name={"optionsContainer"}
              data-plasmic-override={overrides.optionsContainer}
              className={classNames(defaultcss.all, sty.optionsContainer, {
                [sty.optionsContainer__isOpen]: hasVariant(
                  variants,
                  "isOpen",
                  "isOpen"
                )
              })}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <React.Fragment>
                    <SelectBoxPrimary__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__ctJ8B
                      )}
                      value={"value1" as const}
                    >
                      {"Option 1"}
                    </SelectBoxPrimary__Option>

                    <SelectBoxPrimary__Option
                      className={classNames(
                        "__wab_instance",
                        sty.option__gpjza
                      )}
                      value={"value2" as const}
                    >
                      {"Option 2"}
                    </SelectBoxPrimary__Option>
                  </React.Fragment>
                ),
                value: args.children
              })}
            </div>
          </SelectBoxPrimary__Overlay>
        ) : null}
      </div>
    </PlasmicSelectBoxPrimaryContext.Provider>
  ) as React.ReactElement | null;
}

function useBehavior<P extends pp.BaseSelectProps>(
  props: P,
  ref: pp.SelectRef
) {
  if (!("children" in props)) {
    props = {
      ...props,
      children: (
        <React.Fragment>
          <SelectBoxPrimary__Option
            className={classNames("__wab_instance", sty.option__ctJ8B)}
            value={"value1" as const}
          >
            {"Option 1"}
          </SelectBoxPrimary__Option>

          <SelectBoxPrimary__Option
            className={classNames("__wab_instance", sty.option__gpjza)}
            value={"value2" as const}
          >
            {"Option 2"}
          </SelectBoxPrimary__Option>
        </React.Fragment>
      )
    };
  }

  return pp.useSelect(
    PlasmicSelectBoxPrimary,
    props,
    {
      isOpenVariant: { group: "isOpen", variant: "isOpen" },
      placeholderVariant: {
        group: "showPlaceholder",
        variant: "showPlaceholder"
      },
      isDisabledVariant: { group: "isDisabled", variant: "isDisabled" },
      triggerContentSlot: "selectedContent",
      optionsSlot: "children",
      placeholderSlot: "placeholder",
      root: "root",
      trigger: "trigger",
      overlay: "overlay",
      optionsContainer: "optionsContainer"
    },

    ref
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "trigger",
    "contentContainer",
    "dropdownIcon",
    "overlay",
    "optionsContainer"
  ],
  trigger: ["trigger", "contentContainer", "dropdownIcon"],
  contentContainer: ["contentContainer"],
  dropdownIcon: ["dropdownIcon"],
  overlay: ["overlay", "optionsContainer"],
  optionsContainer: ["optionsContainer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  trigger: "button";
  contentContainer: "div";
  dropdownIcon: "svg";
  overlay: typeof SelectBoxPrimary__Overlay;
  optionsContainer: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSelectBoxPrimary__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSelectBoxPrimary__VariantsArgs;
    args?: PlasmicSelectBoxPrimary__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicSelectBoxPrimary__Fetches;
  } & Omit<PlasmicSelectBoxPrimary__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSelectBoxPrimary__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSelectBoxPrimary__ArgProps,
      internalVariantPropNames: PlasmicSelectBoxPrimary__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicSelectBoxPrimary__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSelectBoxPrimary";
  } else {
    func.displayName = `PlasmicSelectBoxPrimary.${nodeName}`;
  }
  return func;
}

export const PlasmicSelectBoxPrimary = Object.assign(
  // Top-level PlasmicSelectBoxPrimary renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    trigger: makeNodeComponent("trigger"),
    contentContainer: makeNodeComponent("contentContainer"),
    dropdownIcon: makeNodeComponent("dropdownIcon"),
    overlay: makeNodeComponent("overlay"),
    optionsContainer: makeNodeComponent("optionsContainer"),

    // Metadata about props expected for PlasmicSelectBoxPrimary
    internalVariantProps: PlasmicSelectBoxPrimary__VariantProps,
    internalArgProps: PlasmicSelectBoxPrimary__ArgProps,

    // Context for sub components
    Context: PlasmicSelectBoxPrimaryContext,

    useBehavior
  }
);

export default PlasmicSelectBoxPrimary;
/* prettier-ignore-end */
