// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import {
  PlasmicAdministration,
  DefaultAdministrationProps
} from "./plasmic/lime_hrm_front/PlasmicAdministration";
import { HTMLElementRefOf } from "@plasmicapp/react-web";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface AdministrationProps extends Omit<DefaultAdministrationProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultAdministrationProps altogether and have
// total control over the props for your component.
interface AdministrationProps extends DefaultAdministrationProps {}
var usernameInput = ""

function Administration_(
  props: AdministrationProps,
  ref: HTMLElementRefOf<"div">
) {
  return <PlasmicAdministration root={{ ref }} {...props} 
  usernameInput = {{
    className: "usernameInput",
    onChange: (e: React.FormEvent<HTMLInputElement>) => handleUsernameInput(e)
  }}
  employeeNameInput = {{
    className: "employeeNameInput",
    onChange: (e: React.FormEvent<HTMLInputElement>) => handleEmployeeNameInput(e)
  }}

  />;
}

// const handleSearch = (e: React.FormEvent<HTMLInputElement>) => {
//   search = e.currentTarget.value;
// }

const handleUsernameInput = (e: React.FormEvent<HTMLInputElement>) => {
  usernameInput = e.currentTarget.value;
}

const handleEmployeeNameInput = (e: React.FormEvent<HTMLInputElement>) => {
  employeeNameInput = e.currentTarget.value;
}

const errorCheckBoxes = () => {
 if (usernameInput === "") alert("Please enter an username");
 if (employeeNameInput === "") alert("Please enter an employee name");
const Administration = React.forwardRef(Administration_);
export default Administration;
}
